events {}

http {
        
    include /etc/nginx/mime.types;

    server {
        root /var/www/room-booking;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}